name: Python CI

description: 'Executa testes e checagens básicas para NayulBot'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checagem de sintaxe
        run: |
          python -m compileall .

      - name: Falha se houver erro de sintaxe
        run: |
          if [ $(find . -name '*.pyc' | wc -l) -eq 0 ]; then exit 1; fi
        shell: bash
